%% Internal Condition Vectorization
%
%
%% Code

function [altitude, Mach, Afterburner] = condition_vectorizer(num_conditions)
    % Docstring
    FlightConditions = flight_conditions();
    
    altitude = [FlightConditions.Condition1.altitude,...
                FlightConditions.Condition2.altitude,...
                FlightConditions.Condition3.altitude,...
                FlightConditions.Condition4.altitude,...
                FlightConditions.Condition5.altitude,...
                FlightConditions.Condition6.altitude,...
                FlightConditions.Condition7.altitude,...
                FlightConditions.Condition8.altitude];
    Mach =     [FlightConditions.Condition1.Mach,...
                FlightConditions.Condition2.Mach,...
                FlightConditions.Condition3.Mach,...
                FlightConditions.Condition4.Mach,...
                FlightConditions.Condition5.Mach,...
                FlightConditions.Condition6.Mach,...
                FlightConditions.Condition7.Mach,...
                FlightConditions.Condition8.Mach];
    Afterburner = [FlightConditions.Condition1.Afterburner,...
                   FlightConditions.Condition2.Afterburner,...
                   FlightConditions.Condition3.Afterburner,...
                   FlightConditions.Condition4.Afterburner,...
                   FlightConditions.Condition5.Afterburner,...
                   FlightConditions.Condition6.Afterburner,...
                   FlightConditions.Condition7.Afterburner,...
                   FlightConditions.Condition8.Afterburner];
end