%% Internal Condition Vectorization
%
%
%% Code

function [altitude, Mach, Afterburner] = condition_vectorizer()
    % Docstring
    FlightConditions = flight_conditions();
    
    altitude = [FlightConditions.Condition0.altitude,...
                FlightConditions.Condition1.altitude,...
                FlightConditions.Condition2.altitude,...
                FlightConditions.Condition3.altitude,...
                FlightConditions.Condition4.altitude,...
                FlightConditions.Condition5.altitude,...
                FlightConditions.Condition6.altitude,...
                FlightConditions.Condition7.altitude,...
                FlightConditions.Condition8.altitude,...
                FlightConditions.Condition9.altitude,...
                FlightConditions.Condition10.altitude,...
                FlightConditions.Condition11.altitude,...
                FlightConditions.Condition12.altitude];
    
    Mach =     [FlightConditions.Condition0.Mach,...
                FlightConditions.Condition1.Mach,...
                FlightConditions.Condition2.Mach,...
                FlightConditions.Condition3.Mach,...
                FlightConditions.Condition4.Mach,...
                FlightConditions.Condition5.Mach,...
                FlightConditions.Condition6.Mach,...
                FlightConditions.Condition7.Mach,...
                FlightConditions.Condition8.Mach,...
                FlightConditions.Condition9.Mach,...
                FlightConditions.Condition10.Mach,...
                FlightConditions.Condition11.Mach,...
                FlightConditions.Condition12.Mach];
    
    Afterburner = [FlightConditions.Condition0.Afterburner,...
                   FlightConditions.Condition1.Afterburner,...
                   FlightConditions.Condition2.Afterburner,...
                   FlightConditions.Condition3.Afterburner,...
                   FlightConditions.Condition4.Afterburner,...
                   FlightConditions.Condition5.Afterburner,...
                   FlightConditions.Condition6.Afterburner,...
                   FlightConditions.Condition7.Afterburner,...
                   FlightConditions.Condition8.Afterburner,...
                   FlightConditions.Condition9.Afterburner,...
                   FlightConditions.Condition10.Afterburner,...
                   FlightConditions.Condition11.Afterburner,...
                   FlightConditions.Condition12.Afterburner];
end