%% Flight Conditions
%
% INSERT DOC
%% CODE
function [conditions] = flight_conditions()
    % Altitude: [ft]
    % Mach as per Atmos
    
    % Takeoff Appendix 2-3
    Condition1 = struct('altitude', 0, ...
                        'Mach', 0.3542,...
                        'Afterburner', 'ON');
    % Refueling A3-3 & Buddy Mission A4-2
    Condition2 = struct('altitude', 25000, ...
                        'Mach', 0.75,...
                        'Afterburner', 'OFF');
                    
    % Climbing A3-3
    Condition3 = struct('altitude', 30000, ...
                        'Mach', 1.25,...
                        'Afterburner', 'ON');
    
    % Concorde Flight Conditions
    Condition4 = struct('altitude', 60000, ...
                        'Mach', 2.00,...
                        'Afterburner', 'ON');
                    
    % YF12A Record Flight 03/18/65
    Condition5 = struct('altitude', 65000, ...
                        'Mach', 2.2,...
                        'Afterburner', 'ON');
                    
    % A12 Max. Altitude at M=2.2
    Condition6 = struct('altitude', 75500, ...
                        'Mach', 2.2,...
                        'Afterburner', 'ON');  
                    
    % Takeoff at high altitude airstrip (Lake County Airport)
    Condition7 = struct('altitude', 9928, ...
                        'Mach', 0.3545,...
                        'Afterburner', 'ON');
    
    % Lowest operating altitude at M=1.0
    Condition8 = struct('altitude', 15000, ...
                        'Mach', 1.00,...
                        'Afterburner', 'ON');                
    conditions = struct('Condition1', Condition1,...
                        'Condition2', Condition2,...
                        'Condition3', Condition3,...
                        'Condition4', Condition4,...
                        'Condition5', Condition5,...
                        'Condition6', Condition6,...
                        'Condition7', Condition7,...
                        'Condition8', Condition8);
end
