%% Flight Conditions
%
% INSERT DOC
%% CODE
function [conditions] = flight_conditions()
    % Altitude: [ft]
    % Mach as per Atmos
    
    % Takeoff Appendix 2-3
    Condition1 = struct('altitude', 0, ...
                        'Mach', 0.3542,...
                        'Afterburner', 'ON');
    % Refueling A3-3 & Buddy Mission A4-2
    Condition2 = struct('altitude', 25000, ...
                        'Mach', 0.75,...
                        'Afterburner', 'OFF');
                    
    % Climbing A3-3
    Condition3 = struct('altitude', 30000, ...
                        'Mach', 1.25,...
                        'Afterburner', 'ON');
    
    % Concorde Flight Conditions
    Condition4 = struct('altitude', 60039, ...
                        'Mach', 2.02,...
                        'Afterburner', 'ON');
                    
    conditions = struct('Condition1', Condition1,...
                        'Condition2', Condition2,...
                        'Condition3', Condition3,...
                        'Condition4', Condition4);
end