%% Flight Conditions
%
% INSERT DOC
%% CODE
function [conditions] = flight_conditions()
    % Altitude: [ft]
    % Mach as per Atmos
    
    % Takeoff Appendix 2-3
    Condition1 = struct('altitude', 0, ...
                        'Mach', 0.3542,...
                        'Afterburner', 1);
    % Refueling A3-3 & Buddy Mission A4-2
    Condition2 = struct('altitude', 25000, ...
                        'Mach', 0.75,...
                        'Afterburner', 0);
                    
    % Climbing A3-3
    Condition3 = struct('altitude', 30000, ...
                        'Mach', 1.25,...
                        'Afterburner', 1);
    
    % Concorde Flight Conditions
    Condition4 = struct('altitude', 60000, ...
                        'Mach', 2.00,...
                        'Afterburner', 1);
                    
    % YF12A Record Flight 03/18/65
    Condition5 = struct('altitude', 65000, ...
                        'Mach', 2.2,...
                        'Afterburner', 1);
                    
    % A12 Max. Altitude at M=2.2
    Condition6 = struct('altitude', 75500, ...
                        'Mach', 2.2,...
                        'Afterburner', 1);  
                    
    % Takeoff at high altitude airstrip (Lake County Airport)
    Condition7 = struct('altitude', 9928, ...
                        'Mach', 0.3545,...
                        'Afterburner', 1);
    
    % Lowest operating altitude at M=1.0
    Condition8 = struct('altitude', 15000, ...
                        'Mach', 1.00,...
                        'Afterburner', 1); 
     % MA139-XAA
    Condition9 = struct('altitude', 40000, ...
                        'Mach', 1.9,...
                        'Afterburner', 1);
                    
    % French Griffon II
    Condition10 = struct('altitude', 6100, ...
                        'Mach', 2.1,...
                        'Afterburner', 1);
                    
    % Constant climb
    Condition11 = struct('altitude', 33000, ...
                        'Mach', 0.9,...
                        'Afterburner', 1);  
                    
    % Supersonic transport flight
    Condition12 = struct('altitude', 70000 ...
                        'Mach', 2.5,...
                        'Afterburner', 0);
    

    conditions = struct('Condition1', Condition1,...
                        'Condition2', Condition2,...
                        'Condition3', Condition3,...
                        'Condition4', Condition4,...
                        'Condition5', Condition5,...
                        'Condition6', Condition6,...
                        'Condition7', Condition7,...
                        'Condition8', Condition8,...
                        'Condition9', Condition9,...
                        'Condition10', Condition10,...
                        'Condition11', Condition11,...
                        'Condition12', Condition12);
end
